export const INGREDIENTS = [
  // Vegetables
  'Tomato',
  'Onion',
  'Garlic',
  'Bell Pepper',
  'Cucumber',
  'Carrot',
  'Broccoli',
  'Spinach',
  'Kale',
  'Lettuce',
  'Zucchini',
  'Mushroom',
  'Eggplant',
  'Green Beans',
  'Peas',
  'Corn',
  'Cabbage',
  'Cauliflower',
  'Asparagus',
  'Artichoke',
  'Beet',
  'Radish',
  'Turnip',
  'Celery',
  'Leek',
  'Bok Choy',
  'Swiss Chard',
  'Arugula',
  'Brussels Sprouts',
  'Potato',
  'Sweet Potato',

  // Legumes
  'Chickpea',
  'Black Bean',
  'Pinto Bean',
  'Kidney Bean',
  'Lentil',
  'Red Lentil',
  'Green Lentil',
  'Split Pea',
  'Navy Bean',
  'Peanut',

  // Grains & Pasta
  'Rice',
  'Brown Rice',
  'Quinoa',
  'Couscous',
  'Pasta',
  'Whole Wheat Pasta',
  'Noodle',
  'Oat',
  'Barley',
  'Millet',
  'Buckwheat',

  // Dairy & Alternatives
  'Milk',
  'Yogurt',
  'bread',
  'Cheese',
  'Cream Cheese',
  'Mozzarella',
  'Cheddar',
  'Feta',
  'Paneer',
  'Butter',
  'Ghee',
  'Coconut Milk',
  'Almond Milk',
  'Soy Milk',
  'Oat Milk',

  // Proteins
  'Tofu',
  'Tempeh',
  'Seitan',
  'Egg',
  'Edamame',

  // Nuts & Seeds
  'Almond',
  'Cashew',
  'Walnut',
  'Pecan',
  'Pine Nut',
  'Pumpkin Seed',
  'Sunflower Seed',
  'Sesame Seed',
  'Chia Seed',
  'Flax Seed',
  'Hemp Seed',

  // Fruits
  'Apple',
  'Banana',
  'Orange',
  'Lemon',
  'Lime',
  'Avocado',
  'Strawberry',
  'Blueberry',
  'Mango',
  'Pineapple',
  'Pomegranate',
  'Grape',
  'Watermelon',
  'Papaya',
  'Coconut',
  'Date',
  'Fig',

  // Herbs & Spices
  'Basil',
  'Cilantro',
  'Parsley',
  'Dill',
  'Thyme',
  'Oregano',
  'Sage',
  'Rosemary',
  'Mint',
  'Cumin',
  'Coriander',
  'Turmeric',
  'Paprika',
  'Chili Powder',
  'Black Pepper',
  'Cinnamon',
  'Ginger',
  'Nutmeg',
  'Clove',
  'Cardamom',
  'Bay Leaf',
  'Star Anise',
  'Saffron',
  'Vanilla',

  // Condiments & Oils
  'Olive Oil',
  'Coconut Oil',
  'Sesame Oil',
  'Soy Sauce',
  'Tamari',
  'Vinegar',
  'Balsamic Vinegar',
  'Apple Cider Vinegar',
  'Honey',
  'Maple Syrup',
  'Agave Nectar',
  'Tomato Paste',
  'Tomato Sauce',
  'Hot Sauce',
  'Mustard',
  'Peanut Butter',
  'Almond Butter',
  'Tahini',
]

export const DIETARY_FILTERS = [
  { id: 'vegan', label: 'Vegan (No animal products)' },
  { id: 'gluten-free', label: 'Gluten-Free' },
  { id: 'dairy-free', label: 'Dairy-Free' },
  { id: 'nut-free', label: 'Nut-Free' },
  { id: 'soy-free', label: 'Soy-Free' },
  { id: 'high-protein', label: 'High-Protein' },
  { id: 'low-carb', label: 'Low-Carb' },
]
